# Configuraci贸n del servidor
server:
  port: 8081
  error:
    include-message: always

# Configuraci贸n de Spring
spring:
  # Configuraci贸n de migraci贸n de base de datos con Flyway
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://ep-empty-silence-a8yu855q.eastus2.azure.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: j4XaGMgL2qbl
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
