CREATE TABLE IF NOT EXISTS sensors (
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
type VARCHAR(20) NOT NULL,
user_id INT NOT NULL,
location VARCHAR(100),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
 );

CREATE TABLE IF NOT EXISTS alerts (
id SERIAL PRIMARY KEY,
sensors_id INT NOT NULL,
alerts_type VARCHAR(30) NOT NULL,
message TEXT,
alerts_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
resolved BOOLEAN NOT NULL DEFAULT FALSE,
FOREIGN KEY (sensors_id) REFERENCES sensors(id) ON DELETE CASCADE
 );